version: 2.1

workflows:
  version: 2

  test:
    jobs:
      - checkout_code
      - bundle_install:
          requires:
            - checkout_code
      - rspec:
          requires:
            - bundle_install
      - rubocop:
          requires:
            - bundle_install
      - bundle_audit:
          requires:
            - bundle_install

executors:
  ruby:
    docker:
      - image: circleci/ruby:2.5
        environment:
          BUNDLE_PATH: vendor/bundle
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          RAILS_ENV: test

jobs:
  checkout_code:
    executor: ruby
    steps:
      - attach_workspace:
          at: .
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  bundle_install:
    executor: ruby
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - imgproxy-rb-bundle-{{ checksum "imgproxy.gemspec" }}-{{ .Environment.CIRCLE_CACHE_VER }}
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: Bundle Install
          command: bundle check || bundle install --frozen --with test
      - save_cache:
          key: imgproxy-rb-bundle-{{ checksum "imgproxy.gemspec" }}-{{ .Environment.CIRCLE_CACHE_VER }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle

  rspec:
    executor: ruby
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run RSpec
          command: |
            bundle exec rspec --format RspecJunitFormatter --out /tmp/test-results/rspec.xml \
                              --format progress \
                              --no-color

      - store_test_results:
          path: /tmp/test-results

  rubocop:
    executor: ruby
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Rubocop
          command: bundle exec rubocop

  bundle_audit:
    executor: ruby
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run bundled gems audit
          command: bundle exec bundle-audit update && bundle exec bundle-audit check
